CREATE TABLE IF NOT EXISTS informes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  notas TEXT NOT NULL,
  plantilla TEXT NOT NULL,
  tono TEXT NOT NULL,
  informe TEXT NOT NULL,
  modelo TEXT,
  creado_en DATETIME DEFAULT CURRENT_TIMESTAMP
);
